{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite.fullname" . }}-redis
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: tcp-redis
      protocol: TCP
      name: tcp-redis
  selector:
    {{- include "ignite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
